package com.ptc.model;

// Generated 2 Jun, 2015 3:00:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", catalog = "school_db")
public class School implements java.io.Serializable {

	private Integer id;
	private String name;
	private String plotNo;
	private Integer localityId;
	private String street;
	private String landmark;
	private String pincode;
	private Float longitude;
	private Float latitude;
	private String alias;
	private String tagLine;
	private String aboutSchool;
	private String logo;
	private Byte establishmentType;
	private Boolean status;
	private Date liveDate;
	private Date createdBy;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set studentSchoolInfos = new HashSet(0);
	private Set timeTables = new HashSet(0);
	private Set studentProfiles = new HashSet(0);
	private Set schoolTeachers = new HashSet(0);
	private Set studentPrevSchoolDetails = new HashSet(0);
	private Set classInfos = new HashSet(0);
	private Set classSubjectses = new HashSet(0);

	public School() {
	}

	public School(String name, String plotNo, Integer localityId,
			String street, String landmark, String pincode, Float longitude,
			Float latitude, String alias, String tagLine, String aboutSchool,
			String logo, Byte establishmentType, Boolean status, Date liveDate,
			Date createdBy, Date lastUpdatedOn, Integer lastUpdatedBy,
			Set studentSchoolInfos, Set timeTables, Set studentProfiles,
			Set schoolTeachers, Set studentPrevSchoolDetails, Set classInfos,
			Set classSubjectses) {
		this.name = name;
		this.plotNo = plotNo;
		this.localityId = localityId;
		this.street = street;
		this.landmark = landmark;
		this.pincode = pincode;
		this.longitude = longitude;
		this.latitude = latitude;
		this.alias = alias;
		this.tagLine = tagLine;
		this.aboutSchool = aboutSchool;
		this.logo = logo;
		this.establishmentType = establishmentType;
		this.status = status;
		this.liveDate = liveDate;
		this.createdBy = createdBy;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.studentSchoolInfos = studentSchoolInfos;
		this.timeTables = timeTables;
		this.studentProfiles = studentProfiles;
		this.schoolTeachers = schoolTeachers;
		this.studentPrevSchoolDetails = studentPrevSchoolDetails;
		this.classInfos = classInfos;
		this.classSubjectses = classSubjectses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "plot_no", length = 100)
	public String getPlotNo() {
		return this.plotNo;
	}

	public void setPlotNo(String plotNo) {
		this.plotNo = plotNo;
	}

	@Column(name = "locality_id")
	public Integer getLocalityId() {
		return this.localityId;
	}

	public void setLocalityId(Integer localityId) {
		this.localityId = localityId;
	}

	@Column(name = "street", length = 500)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "landmark", length = 150)
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "pincode", length = 100)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "longitude", precision = 9, scale = 3)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 9, scale = 3)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "alias", length = 200)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "tag_line", length = 200)
	public String getTagLine() {
		return this.tagLine;
	}

	public void setTagLine(String tagLine) {
		this.tagLine = tagLine;
	}

	@Column(name = "about_school", length = 65535)
	public String getAboutSchool() {
		return this.aboutSchool;
	}

	public void setAboutSchool(String aboutSchool) {
		this.aboutSchool = aboutSchool;
	}

	@Column(name = "logo", length = 200)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "establishment_type")
	public Byte getEstablishmentType() {
		return this.establishmentType;
	}

	public void setEstablishmentType(Byte establishmentType) {
		this.establishmentType = establishmentType;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "live_date", length = 10)
	public Date getLiveDate() {
		return this.liveDate;
	}

	public void setLiveDate(Date liveDate) {
		this.liveDate = liveDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_by", length = 10)
	public Date getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Date createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_on", length = 10)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getStudentSchoolInfos() {
		return this.studentSchoolInfos;
	}

	public void setStudentSchoolInfos(Set studentSchoolInfos) {
		this.studentSchoolInfos = studentSchoolInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getTimeTables() {
		return this.timeTables;
	}

	public void setTimeTables(Set timeTables) {
		this.timeTables = timeTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getStudentProfiles() {
		return this.studentProfiles;
	}

	public void setStudentProfiles(Set studentProfiles) {
		this.studentProfiles = studentProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getSchoolTeachers() {
		return this.schoolTeachers;
	}

	public void setSchoolTeachers(Set schoolTeachers) {
		this.schoolTeachers = schoolTeachers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getStudentPrevSchoolDetails() {
		return this.studentPrevSchoolDetails;
	}

	public void setStudentPrevSchoolDetails(Set studentPrevSchoolDetails) {
		this.studentPrevSchoolDetails = studentPrevSchoolDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getClassInfos() {
		return this.classInfos;
	}

	public void setClassInfos(Set classInfos) {
		this.classInfos = classInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getClassSubjectses() {
		return this.classSubjectses;
	}

	public void setClassSubjectses(Set classSubjectses) {
		this.classSubjectses = classSubjectses;
	}

}
