package com.ptc.model;

// Generated 2 Jun, 2015 3:00:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "school_db")
public class Subject implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;
	private Set timeTables = new HashSet(0);
	private Set classSubjectses = new HashSet(0);
	private Set teacherSubjects = new HashSet(0);

	public Subject() {
	}

	public Subject(String name, Date lastUpdatedOn, Integer lastUpdatedBy,
			Set timeTables, Set classSubjectses, Set teacherSubjects) {
		this.name = name;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.timeTables = timeTables;
		this.classSubjectses = classSubjectses;
		this.teacherSubjects = teacherSubjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_on", length = 10)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set getTimeTables() {
		return this.timeTables;
	}

	public void setTimeTables(Set timeTables) {
		this.timeTables = timeTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set getClassSubjectses() {
		return this.classSubjectses;
	}

	public void setClassSubjectses(Set classSubjectses) {
		this.classSubjectses = classSubjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set getTeacherSubjects() {
		return this.teacherSubjects;
	}

	public void setTeacherSubjects(Set teacherSubjects) {
		this.teacherSubjects = teacherSubjects;
	}

}
